version: "3"
services:
  jekyll:
    container_name: website
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
