name: CI

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4

      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid

      - name: Prettier Check
        id: prettier
        run: npx prettier . --check

      - name: Create diff
        if: ${{ failure() }}
        run: |
          npx prettier . --write
          git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
          npm install -g diff2html-cli
          diff2html -i file -s side -F diff.html -- diff.txt

      - name: Upload html diff
        id: artifact-upload
        if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: HTML Diff
          path: diff.html
          retention-days: 7

      - name: Dispatch information to repository
        if: ${{ failure() && steps.prettier.conclusion == 'failure' && github.event_name == 'pull_request' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: prettier-failed-on-pr
          client-payload: '{"pr_number": "${{ github.event.number }}", "artifact_url": "${{ steps.artifact-upload.outputs.artifact-url }}", "run_id": "${{ github.run_id }}"}'

  check-links-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          # removed md files that include liquid tags
          args: --exclude-path --verbose --no-progress './**/*.md' './**/*.html'

  check-links-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Update _config.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          changes: |
            {
              "baseurl": ""
            }

      - name: Install and Build
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build --lsi

      - name: Purge unused CSS
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --offline --remap '_site(/?.*)/assets/(.*) _site/assets/$2' --verbose --no-progress '_site/**/*.html'

  mock-deploy:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: [prettier, check-links-remote, check-links-local]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Install and Build
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build --lsi

      - name: Purge unused CSS
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

  actual-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [prettier, check-links-remote, check-links-local]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Install and Build
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build --lsi

      - name: Purge unused CSS
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
