name: CI

on:
  push:
    branches: ["master"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and Publish
        uses: nelsonjchen/gh-pages-pelican-action@0.2.0
        with:
          GH_PAGES_CNAME: jonpoulton.dev
